name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Chekout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#frontend image build and push

    - name: Build and push frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

#backend image build and push

    - name: Build and push backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}/backend:latest
          ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}/backend:${{ github.sha }}

    - name: Azure login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get VM IP
      run: |
          IP=$(az vm show -d -g Project-Directory -n public-vm --query publicIps -o tsv)
          echo "VM_IP=$IP" >> $GITHUB_ENV

    - name: SSH into VM and clone repo
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem CodeMagicians@${{ env.VM_IP }} "
            git clone https://token:${{ secrets.GH_PAT }}@github.com/Zakaria-Belkouche/Azure-Project.git || true
            cd Azure-Project
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
            docker compose up -d
          "

